[package]
name = "diag"
version = "0.7.0"
edition = "2021"
authors = ["Adam Szkoda <adaszko@gmail.com>"]
description = "Directed Acyclic Graphs with integer vertices represented as a Strictly Upper Triangular Matrix stored in a bit set"
homepage = "https://github.com/adaszko/diag"
repository = "https://github.com/adaszko/diag"
keywords = ["dag", "graph"]
license = "GPL-3.0"


[dependencies]
fixedbitset = "0.4"
rand = "0.8.4"
rand_distr = "0.4.3"
quickcheck = "1"

[dev-dependencies]
quickcheck = "1"
